function sayHello(name,age) {
    console.log("Hello"+name+age);
    console.log("Youre age is " + age)
}

sayHello("Marius", 20)

sayHello("Andrius", 45)

function addNumbers(x,y) {
    const sum =  x + y;
    return sum;

}
console.log(addNumbers(1,2));


// function checkAge(age) {
//     if (age>18) {
//         return true;
    // } else {
        // return confirm("Ar tikrai?");
    // }
// }

// console.log(checkAge(17));




